workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "ExpoApp.xcworkspace"
        XCODE_SCHEME: "ExpoApp"
        BUNDLE_ID: "io.codemagic.expoapp"
    node: 20.11.1
    xcode: 16.1
    cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install dependencies, Expo CLI and eject app
        script: |
          yarn install
          yarn global add expo-cli
          expo eject
      - name: Build IPA
        script: |
          xcodebuild -workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
                    -scheme "$XCODE_SCHEME" \
                    -configuration Release \
                    -archivePath "$CM_BUILD_DIR/ios/Archives/$XCODE_SCHEME.xcarchive" \
                    -exportOptionsPlist ios/ExportOptions.plist \
                    build
    artifacts:
      - build/ios/ipa/*.ipa