workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "ExpoApp.xcworkspace"
        XCODE_SCHEME: "ExpoApp"
        BUNDLE_ID: "io.codemagic.expoapp"
    scripts:
      - name: Install dependencies, Expo CLI and eject app
        script: |
          yarn install
          yarn global add expo-cli
          expo eject
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/IPA/*.ipa